// server-lib/tables-report.js  —  Report-related table creation functions (cuadre, close, dashboard cache)
import { pool } from "./core.js";

async function ensureCuadreCajaTable() { await pool.query(`CREATE TABLE IF NOT EXISTS cuadre_caja (id_cuadre INT NOT NULL AUTO_INCREMENT, fecha DATE NOT NULL, id_bodega INT NOT NULL, sede VARCHAR(120) NULL, responsable VARCHAR(120) NULL, payload_json LONGTEXT NOT NULL, total_efectivo DECIMAL(14,2) NOT NULL DEFAULT 0, total_cobro DECIMAL(14,2) NOT NULL DEFAULT 0, total_venta_ambiente DECIMAL(14,2) NOT NULL DEFAULT 0, gran_total_reporte DECIMAL(14,2) NOT NULL DEFAULT 0, creado_por INT NULL, actualizado_por INT NULL, creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id_cuadre), UNIQUE KEY uq_cuadre_caja_fecha_bodega (fecha, id_bodega), KEY idx_cuadre_caja_bodega_fecha (id_bodega, fecha)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`); }
async function ensureDashboardCacheTable() { await pool.query(`CREATE TABLE IF NOT EXISTS dashboard_cache_resumen (scope_key VARCHAR(80) NOT NULL, id_bodega INT NULL, dias INT NOT NULL, mov_days INT NOT NULL, payload_json LONGTEXT NOT NULL, generado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (scope_key), KEY idx_cache_generado (generado_en), KEY idx_cache_bodega (id_bodega)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`); }
async function ensureDailyCloseTables() {
  await pool.query(`CREATE TABLE IF NOT EXISTS cierre_dia (id_cierre BIGINT NOT NULL AUTO_INCREMENT, id_bodega INT NOT NULL, fecha_cierre DATE NOT NULL, total_entradas DECIMAL(18,3) NOT NULL DEFAULT 0, total_salidas DECIMAL(18,3) NOT NULL DEFAULT 0, total_existencia_cierre DECIMAL(18,3) NOT NULL DEFAULT 0, creado_por INT NULL, origen ENUM('MANUAL','AUTO') NOT NULL DEFAULT 'MANUAL', observaciones VARCHAR(255) NULL, creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id_cierre), UNIQUE KEY uq_cierre_bodega_fecha (id_bodega, fecha_cierre), KEY idx_cierre_bodega_fecha (id_bodega, fecha_cierre)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await pool.query(`CREATE TABLE IF NOT EXISTS cierre_dia_detalle (id_cierre_detalle BIGINT NOT NULL AUTO_INCREMENT, id_cierre BIGINT NOT NULL, id_producto INT NOT NULL, sku VARCHAR(80) NULL, nombre_producto VARCHAR(180) NULL, existencia_inicial DECIMAL(18,3) NOT NULL DEFAULT 0, entradas_dia DECIMAL(18,3) NOT NULL DEFAULT 0, salidas_dia DECIMAL(18,3) NOT NULL DEFAULT 0, existencia_cierre DECIMAL(18,3) NOT NULL DEFAULT 0, PRIMARY KEY (id_cierre_detalle), KEY idx_detalle_cierre (id_cierre), KEY idx_detalle_producto (id_producto), CONSTRAINT fk_cierre_detalle_cierre FOREIGN KEY (id_cierre) REFERENCES cierre_dia(id_cierre) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
}

export { ensureCuadreCajaTable, ensureDashboardCacheTable, ensureDailyCloseTables };
